### ISSUE TITLE
Broken link "di-internships.md" in Readme.md

### ISSUE THREAD

**Issue by sstegaru** [svaksha/50-DI#1]
Hi!

I just noticed that the link in the following bullet from the Readme.md is broken:
"di-internships.md :: Summer of Code programs and internships open to women applicants."

It links to a non-existant file called "di-foss-internships.md", which seems to have been renamed to "di-internships.md" (just as the caption suggests), but it wasn't updated in this case.

Best regards,
Silvia

**Comment by svaksha** [comment]
Thanks for the alert. Fixed with the latest commit.
Cheers,
