### ISSUE TITLE
Add "Tech Initiatives for marginalized groups"

### ISSUE THREAD

**Issue by hargup** [svaksha/50-DI#3]
I noticed  **[Tech Initiatives for marginalized groups](https://gist.github.com/anikalindtner/9524950)** list by  [anikalindtner](https://github.com/anikalindtner), you can probably make some additions from that list to your repo.

**Comment by svaksha** [comment]
Thanks, done! JFTR, I've linked it instead of adding content from there as it had [no licence](http://choosealicense.com/no-license/). Read, cannot copy content afaiu.
